name: Dynamic workflow generation
on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        description: "Repository to commit the dynamic workflow. For example, taviscasolutions-poc/DB-Backup-Restore"
        type: string
#       repository_pat:
#         required: true
#         description: "Github PAT token required to commit to the repository"
#         type: string
      type_of_database:
        required: true
        type: choice
        options:
        - cassandra
        - dynamodb
        default: dynamodb
      operation:
        required: true
        type: choice
        options:
        - backup
        - restore
        default: backup
permissions:
  contents: write
jobs:
  generate-dynamic-workflow:
    runs-on: ubuntu-latest
    outputs:
      workflow_file_name: ${{ steps.generate-workflow.outputs.workflow_file_name }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GHPAT}} #required for github action to commit the file to workflow directory

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::928814396842:role/github-actions-restore-poc-role
      #     role-duration-seconds: 900
      #     aws-region: us-east-1

      - name: Generate workflow
        id: generate-workflow
        env:
          repository: ${{inputs.repository}}
          pat: ${{inputs.repository_pat}}
        run: |
          python convert.py -d ${{inputs.type_of_database}} -o ${{inputs.operation}}

      - name: Commit and Push new workflow file
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull origin main
          git add .
          git commit -m "new workflow file created - ${{steps.generate-workflow.outputs.workflow_file_name}}"
          git push origin main

      - name: Print workflow file output
        env:
          OUTPUT: ${{steps.generate-workflow.outputs.workflow_file_name}}
        run: |
          echo "$OUTPUT"
